<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <RepositoryUrl>https://github.com/rambotech/BOG.FolderManifest</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>folder_eye.ico</PackageIcon>
    <RepositoryType>git</RepositoryType>
    <PackageTags>folder;manifest;files;names;shell; explorer</PackageTags>
    <AssemblyVersion>1.1.0.0</AssemblyVersion>
    <FileVersion>1.1.0.0</FileVersion>
    <Description>A winform shell extension for folders to build file manifest (deployments, etc)</Description>
    <Copyright>(c)2013-2026 John J Schultz</Copyright>
    <Title>Folder Manifest builder</Title>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BOG.SwissArmyKnife" Version="1.9.2" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Update="ico\folder_eye.ico">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="start_me.bat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="template\FolderManifest_Apply_ShellExt.reg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="template\FolderManifest_Remove_ShellExt.reg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>